//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piton_Ar_ge_ve_Yazılım_Evi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YapilacakIsler
    {
        public System.Guid Id { get; set; }
        public string YapilacakIs { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> BaslangicTarih { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<int> Drum { get; set; }
    }
}
